# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='权限名称')),
                ('description', models.TextField(verbose_name='权限详情介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Vip的名字')),
                ('level', models.IntegerField(verbose_name='会员等级')),
                ('price', models.FloatField(verbose_name='会员的价格')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='VipPermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.IntegerField(verbose_name='Vip的ID')),
                ('perm_id', models.IntegerField(verbose_name='Permission的ID')),
            ],
        ),
    ]
