# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='好友ID 1')),
                ('uid2', models.IntegerField(verbose_name='好友ID 2')),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的 UID')),
                ('sid', models.IntegerField(verbose_name='被滑动者的 UID')),
                ('stype', models.CharField(choices=[('dislike', '左滑'), ('like', '右滑'), ('superlike', '上滑')], max_length=10, verbose_name='滑动类型')),
                ('stime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
